#!/bin/bash

mkdir ~/Uni/2.MAILA/ISO/PROJECT/IOS/Home

mkdir ~/Uni/2.MAILA/ISO/PROJECT/IOS/Home/WesternForest

mkdir ~/Uni/2.MAILA/ISO/PROJECT/IOS/Home/NorthernMeadow

mkdir ~/Uni/2.MAILA/ISO/PROJECT/IOS/Home/WesternForest/SpellCastingAcademy

mkdir ~/Uni/2.MAILA/ISO/PROJECT/IOS/Home/WesternForest/SpellCastingAcademy/Lessons

mkdir ~/Uni/2.MAILA/ISO/PROJECT/IOS/Home/WesternForest/SpellCastingAcademy/PracticeRoom

mkdir ~/Uni/2.MAILA/ISO/PROJECT/IOS/Home/NorthernMeadow/EasternMountains

mkdir ~/Uni/2.MAILA/ISO/PROJECT/IOS/Home/NorthernMeadow/Cave

chmod 444 ~/Uni/2.MAILA/ISO/PROJECT/IOS/Home/NorthernMeadow

